# Generated by Django 4.1.1 on 2022-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(default=0)),
                ('product_description', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='./productsimg')),
            ],
        ),
    ]
